kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reloader-role-binding
  labels:
    app: reloader
subjects:
  - kind: ServiceAccount
    name: reloader-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reloader-role
