kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reloader-role
  labels:
    app: reloader
rules:
- verbs:
  - list
  - get
  - watch
  apiGroups:
  - ''
  resources:
  - secrets
  - configmaps
- verbs:
  - list
  - get
  - update
  - patch
  apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
- verbs:
  - list
  - get
  - update
  - patch
  apiGroups:
  - extensions
  resources:
  - deployments
  - daemonsets
- verbs:
  - list
  - get
  apiGroups:
  - batch
  resources:
  - cronjobs
- verbs:
  - create
  apiGroups:
  - batch
  resources:
  - jobs
- verbs:
  - create
  - patch
  apiGroups:
  - ''
  resources:
  - events
